"""Add is_deleted to sip_trunks and sip_calls for soft deletes

Revision ID: 0d7f6660b9d3
Revises: 4160d581fc26
Create Date: 2025-09-22 12:52:59.796482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7f6660b9d3'
down_revision: Union[str, None] = '4160d581fc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sip_calls', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.sql.false()))
    op.add_column('sip_trunks', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.sql.false()))
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.drop_column('sip_trunks', 'is_deleted')
    op.drop_column('sip_calls', 'is_deleted')
    # ### end Alembic commands ###