"""Fix AgentKnowledgeMapping primary key and foreign key cascade

Revision ID: 2e696d1b8cea
Revises: 79e21ad17db1
Create Date: 2025-08-27 01:47:57.568801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e696d1b8cea'
down_revision: Union[str, None] = '79e21ad17db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_knowledge_mappings_knowledge_base_id_fkey'), 'agent_knowledge_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'agent_knowledge_mappings', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.drop_column('agent_knowledge_mappings', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_knowledge_mappings', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agent_knowledge_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('agent_knowledge_mappings_knowledge_base_id_fkey'), 'agent_knowledge_mappings', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###
