"""Add cascade delete to documents table

Revision ID: 3917d0fe7801
Revises: adddba93f811
Create Date: 2025-09-01 20:14:29.331110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3917d0fe7801'
down_revision: Union[str, None] = 'adddba93f811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_knowledge_base_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_knowledge_base_id_fkey'), 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###
