"""Add provider column to llm_providers, tts_providers, stt_providers

Revision ID: 5ded2931ce14
Revises: 4ce3a1d0277a
Create Date: 2025-08-21 15:54:10.808344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ded2931ce14'
down_revision: Union[str, None] = '4ce3a1d0277a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
