"""Add call_id to connections table

Revision ID: 632ea0c94fb2
Revises: 17ea788598a0
Create Date: 2025-09-06 04:03:48.355070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632ea0c94fb2'
down_revision: Union[str, None] = '17ea788598a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('call_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_connections_call_id'), 'connections', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_call_id'), table_name='connections')
    op.drop_column('connections', 'call_id')
    # ### end Alembic commands ###
