"""add is_deleted to agent profile and remove cascade

Revision ID: 64c866508d17
Revises: 632ea0c94fb2
Create Date: 2025-09-10 23:05:38.265137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c866508d17'
down_revision: Union[str, None] = '632ea0c94fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_profiles', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_constraint(op.f('call_logs_agent_id_fkey'), 'call_logs', type_='foreignkey')
    op.create_foreign_key(None, 'call_logs', 'agent_profiles', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.create_foreign_key(op.f('call_logs_agent_id_fkey'), 'call_logs', 'agent_profiles', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('agent_profiles', 'is_deleted')
    # ### end Alembic commands ###
