"""Add ON DELETE CASCADE to agent_profiles foreign keys

Revision ID: 79e21ad17db1
Revises: cceffa76e8e3
Create Date: 2025-08-27 01:23:54.248290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e21ad17db1'
down_revision: Union[str, None] = 'cceffa76e8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_knowledge_mappings_agent_profile_id_fkey'), 'agent_knowledge_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'agent_knowledge_mappings', 'agent_profiles', ['agent_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('connections_agent_id_fkey'), 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'agent_profiles', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key(op.f('connections_agent_id_fkey'), 'connections', 'agent_profiles', ['agent_id'], ['id'])
    op.drop_constraint(None, 'agent_knowledge_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('agent_knowledge_mappings_agent_profile_id_fkey'), 'agent_knowledge_mappings', 'agent_profiles', ['agent_profile_id'], ['id'])
    # ### end Alembic commands ###
