"""Add is_record to connections table

Revision ID: 86d872174ae6
Revises: 37423d2bc44b
Create Date: 2025-09-05 02:09:10.607307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d872174ae6'
down_revision: Union[str, None] = '37423d2bc44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('is_record', sa.Boolean(), nullable=False, server_default='false'))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'is_record')
    # ### end Alembic commands ###
