"""Add knowledge_bases_data column to connections table

Revision ID: cceffa76e8e3
Revises: d8ac5af8429b
Create Date: 2025-08-26 00:59:26.414341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cceffa76e8e3'
down_revision: Union[str, None] = 'd8ac5af8429b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('knowledge_bases_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'knowledge_bases_data')
    # ### end Alembic commands ###
