"""Add created_at and updated_at columns to agent_profiles

Revision ID: d8ac5af8429b
Revises: 3fa53a651f39
Create Date: 2025-08-25 17:07:28.692046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ac5af8429b'
down_revision: Union[str, None] = '3fa53a651f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('agent_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('agent_profiles', 'llm_provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('agent_profiles', 'tts_provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('agent_profiles', 'stt_provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('connections', 'llm_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('connections', 'tts_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('connections', 'stt_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('connections', 'allow_interruptions',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('connections', 'profile_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('connections', 'interrupt_speech_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('connections', 'interrupt_min_words',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('connections', 'min_endpointing_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('connections', 'max_endpointing_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('connections', 'max_nested_function_calls',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('connections', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('connections', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('connections', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('connections', 'max_nested_function_calls',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('connections', 'max_endpointing_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('connections', 'min_endpointing_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('connections', 'interrupt_min_words',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('connections', 'interrupt_speech_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('connections', 'profile_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('connections', 'allow_interruptions',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('connections', 'stt_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('connections', 'tts_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('connections', 'llm_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('agent_profiles', 'stt_provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('agent_profiles', 'tts_provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('agent_profiles', 'llm_provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('agent_profiles', 'updated_at')
    op.drop_column('agent_profiles', 'created_at')
    # ### end Alembic commands ###
